version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Download appcenter
          command: sudo npm install appcenter-cli -g
      - run:
          name: Login
          command: appcenter login --token 8c9e09a05861982fec691ee04556e4c9bb391f94
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      - run:
          name: Build debug apk
          command: ./gradlew :app:assembleDebug
      - run:
          name: Deliver to appcenter
          command: appcenter distribute release --debug --app piyushgupta77/android_ci_cd_sample --file app/build/outputs/apk/debug/app-debug.apk --group "App Testers"
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples